(() => {
"use strict";
const $=s=>document.querySelector(s);
const canvas=$("#canvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});
const fileInput=$("#fileInput"),solveBtn=$("#solveBtn"),saveBtn=$("#saveBtn"),sizeSelect=$("#sizeSelect"),statusEl=$("#status"),answerEl=$("#answer");
const leftRange=$("#leftRange"),topRange=$("#topRange"),widthRange=$("#widthRange"),leftVal=$("#leftVal"),topVal=$("#topVal"),widthVal=$("#widthVal");
let sourceImage=null,solution=null;
const setStatus=(m,c="muted")=>{statusEl.textContent=m;statusEl.className="status "+c};
function updateVals(){leftVal.textContent=leftRange.value+"%";topVal.textContent=topRange.value+"%";widthVal.textContent=widthRange.value+"%";if(sourceImage)drawSource()}
[leftRange,topRange,widthRange].forEach(x=>x.addEventListener("input",updateVals));
function loadImage(blob){return new Promise((ok,no)=>{const u=URL.createObjectURL(blob),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);ok(im)};im.onerror=e=>{URL.revokeObjectURL(u);no(e)};im.src=u})}
async function useImage(im){sourceImage=im;solution=null;answerEl.textContent="";const s=Math.min(1,1200/im.naturalWidth);canvas.width=Math.round(im.naturalWidth*s);canvas.height=Math.round(im.naturalHeight*s);drawSource();solveBtn.disabled=false;saveBtn.disabled=true;setStatus("圖片已載入。按「自動解題」。")}
fileInput.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{await useImage(await loadImage(f))}catch{setStatus("無法讀取圖片。","err")}});
function rect(){const x=canvas.width*(+leftRange.value/100),y=canvas.height*(+topRange.value/100),w=canvas.width*(+widthRange.value/100),s=Math.min(w,canvas.width-x,canvas.height-y);return{x,y,w:s,h:s}}
function drawSource(){if(!sourceImage)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(sourceImage,0,0,canvas.width,canvas.height);const b=rect();ctx.save();ctx.strokeStyle="rgba(17,24,39,.75)";ctx.lineWidth=Math.max(2,canvas.width/300);ctx.setLineDash([10,8]);ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.restore();if(solution)drawSolution(solution.n,solution.cols,b)}
function drawSolution(n,cols,b){const cw=b.w/n,ch=b.h/n;ctx.save();ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.floor(cw*.52)}px -apple-system,Apple Color Emoji,sans-serif`;ctx.lineWidth=Math.max(3,cw*.055);for(let r=0;r<n;r++){const c=cols[r],x=b.x+(c+.5)*cw,y=b.y+(r+.5)*ch;ctx.beginPath();ctx.arc(x,y,Math.min(cw,ch)*.34,0,Math.PI*2);ctx.strokeStyle="#dc2626";ctx.stroke();ctx.fillText("🐱",x,y+1)}ctx.restore()}
function rgbAt(x,y){const d=ctx.getImageData(Math.max(0,Math.min(canvas.width-1,Math.round(x))),Math.max(0,Math.min(canvas.height-1,Math.round(y))),1,1).data;return[d[0]/255,d[1]/255,d[2]/255]}
const d2=(a,b)=>{const x=a[0]-b[0],y=a[1]-b[1],z=a[2]-b[2];return x*x+y*y+z*z};
const med=a=>{const s=[...a].sort((x,y)=>x-y);return s[Math.floor(s.length/2)]};
const sat=c=>{const M=Math.max(...c),m=Math.min(...c);return M?((M-m)/M):0};
/* Sample mainly around the cell perimeter. This deliberately avoids a large pre-placed cat icon in the centre. */
function sampleCell(b,n,r,c){const cw=b.w/n,ch=b.h/n;const pts=[[.18,.30],[.18,.50],[.18,.70],[.82,.30],[.82,.50],[.82,.70],[.30,.18],[.50,.18],[.70,.18],[.30,.82],[.50,.82],[.70,.82],[.27,.27],[.73,.27],[.27,.73],[.73,.73]];let q=[];for(const[p1,p2]of pts){const v=rgbAt(b.x+(c+p1)*cw,b.y+(r+p2)*ch);if(sat(v)>.07&&Math.max(...v)>.22)q.push(v)}if(!q.length)q=[rgbAt(b.x+(c+.5)*cw,b.y+(r+.5)*ch)];
  /* Find the densest colour family inside the cell; cat/eye/outline pixels become outliers. */
  let best=[];for(const v of q){const g=q.filter(x=>d2(v,x)<0.010);if(g.length>best.length)best=g}if(!best.length)best=q;return[med(best.map(x=>x[0])),med(best.map(x=>x[1])),med(best.map(x=>x[2]))]}
function kmeans(colors,k){let centers=[colors[0]];while(centers.length<k){let best=colors[0],bd=-1;for(const c of colors){const md=Math.min(...centers.map(x=>d2(c,x)));if(md>bd){bd=md;best=c}}centers.push([...best])}let a=new Array(colors.length).fill(0);for(let it=0;it<25;it++){let changed=false;for(let i=0;i<colors.length;i++){let bi=0,bd=1e9;for(let j=0;j<k;j++){const d=d2(colors[i],centers[j]);if(d<bd){bd=d;bi=j}}if(a[i]!==bi){a[i]=bi;changed=true}}const sums=Array.from({length:k},()=>[0,0,0,0]);for(let i=0;i<colors.length;i++){const s=sums[a[i]],c=colors[i];s[0]+=c[0];s[1]+=c[1];s[2]+=c[2];s[3]++}for(let j=0;j<k;j++)if(sums[j][3])centers[j]=[sums[j][0]/sums[j][3],sums[j][1]/sums[j][3],sums[j][2]/sums[j][3]];if(!changed)break}return a}
function buildMap(b,n){const colors=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)colors.push(sampleCell(b,n,r,c));const a=kmeans(colors,n);return Array.from({length:n},(_,r)=>Array.from({length:n},(_,c)=>a[r*n+c]))}
function connected(reg,map){const n=map.length,cells=[];for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(map[r][c]===reg)cells.push([r,c]);if(!cells.length)return false;const seen=new Set([cells[0].join(",")]),q=[cells[0]];for(let i=0;i<q.length;i++){const[r,c]=q[i];for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const nr=r+dr,nc=c+dc,k=nr+","+nc;if(nr>=0&&nc>=0&&nr<n&&nc<n&&map[nr][nc]===reg&&!seen.has(k)){seen.add(k);q.push([nr,nc])}}}return seen.size===cells.length}
function mapQuality(map){const n=map.length;let ok=0;for(let i=0;i<n;i++)if(connected(i,map))ok++;return ok/n}
function solveMap(map,limit=2,nodeLimit=120000){const n=map.length,usedC=new Set(),usedR=new Set(),ans=new Array(n).fill(-1),solutions=[];let nodes=0,aborted=false;function search(rem){if(++nodes>nodeLimit){aborted=true;return}if(solutions.length>=limit||aborted)return;if(!rem.length){solutions.push([...ans]);return}let br=-1,bc=null;for(const row of rem){const cand=[];for(let col=0;col<n;col++){const reg=map[row][col];if(usedC.has(col)||usedR.has(reg))continue;let adj=false;for(let rr=0;rr<n;rr++)if(ans[rr]>=0&&Math.abs(rr-row)<=1&&Math.abs(ans[rr]-col)<=1){adj=true;break}if(!adj)cand.push(col)}if(!cand.length)return;if(bc===null||cand.length<bc.length){br=row;bc=cand}}const next=rem.filter(x=>x!==br);for(const col of bc){const reg=map[br][col];ans[br]=col;usedC.add(col);usedR.add(reg);search(next);usedC.delete(col);usedR.delete(reg);ans[br]=-1;if(solutions.length>=limit||aborted)return}}search(Array.from({length:n},(_,i)=>i));return{solutions,aborted,nodes}}
solveBtn.addEventListener("click",()=>{if(!sourceImage)return;solution=null;drawSource();solveBtn.disabled=true;solveBtn.textContent="解題中…";setStatus("正在辨識與求解…");requestAnimationFrame(()=>setTimeout(()=>{try{const b=rect(),forced=sizeSelect.value==="auto"?null:+sizeSelect.value;const sizes=forced?[forced]:[8,9,10,7,11,12,13,14];let best=null;for(const n of sizes){const map=buildMap(b,n),quality=mapQuality(map);/* Wrong grid sizes usually fragment colour regions; skip expensive search. */if(quality<0.70)continue;const out=solveMap(map,2);if(out.solutions.length){const score=quality+(out.solutions.length===1?.2:0);if(!best||score>best.score)best={n,map,sols:out.solutions,score}}}if(!best)throw new Error("這張圖尚未辨識成功。最常見原因是棋盤上已有貓遮住格色；新版已加強避開貓圖示，請再按一次。若仍失敗，確認棋盤尺寸選對。 ");solution={n:best.n,cols:best.sols[0]};drawSource();saveBtn.disabled=false;sizeSelect.value=String(best.n);answerEl.textContent=best.sols[0].map((c,r)=>`R${r+1}C${c+1}`).join("、");setStatus(`完成：${best.n}×${best.n}，已找到${best.sols.length===1?"唯一":"可行"}解答。`,"ok");statusEl.scrollIntoView({behavior:"smooth",block:"nearest"})}catch(e){setStatus(e.message||"解題失敗。","err");statusEl.scrollIntoView({behavior:"smooth",block:"nearest"})}finally{solveBtn.disabled=false;solveBtn.textContent="自動解題"}},30))});
saveBtn.addEventListener("click",()=>{if(!solution)return;canvas.toBlob(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="meowdoku_answer.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},"image/png")});
updateVals();
})();